modLoader = 'javafml'
loaderVersion = '[40,)'
license = 'LGPL-3.0-only'
logoFile = 'assets/antique_atlas/icon.png'

[properties]
"connector:placeholder"=true

[[mods]]
modId = 'antique_atlas'
version = '${version}'
displayName = 'Antique Atlas'
description = 'An always-accessible abstract world map.'
authors = 'Sisby folk'
displayURL = 'https://modrinth.com/mod/antique-atlas-4'

[[dependencies.antique_atlas]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.antique_atlas]]
modId = "connectormod"
mandatory = true
versionRange = "*"


[[dependencies.antique_atlas]]
modId = "fabric_api"
mandatory = true
versionRange = "${fapi}"
